### PR TITLE
fixed README documentation for function exchangeAuthorizationCode

### PR DESCRIPTION
**Pull request by udaiveerS**
I also factored out callbackURL into a variable because it makes things fit in one line.

### CODE REVIEW

**Comment by udaiveerS** [comment]
Just to clarify I made this pull request because the exchange AuthorizationCode actually takes 3 parameters. 

image
v

**Comment by huckphin** [comment]
@udaiveerS: Thank you for the pull request. Your branch currently has merge conflicts. May I ask you to resolve your merge conflicts, and then let me know when it is ready for another look? Thank you!

**Comment by udaiveerS** [comment]
Hey, I have merged the branches and ran the tests and everything seem ok.

**Comment by huckphin** [comment]
Thanks perfect. Thank you for the contribution.

**Pull request merged**
